### ISSUE TITLE
Setup Recipe App Kanban board

### ISSUE THREAD

**Issue by koomekevo** [koomekevo/recipe-app#12]
**Project Memebers**
- Kevin Koome
- Taro Chilongoshi

This issue has been created to showcase the [Kanban](https://github.com/koomekevo/recipe-app/projects/2) board for our project.

**Comment by dasileker** [comment]
### **Hi @koomekevo,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
